### ISSUE TITLE
Model Format Explanation

### ISSUE THREAD

**Issue by leopeng1995** [dontpanic92/OpenPAL3#10]
这几天我都在看仙剑3的游戏资源文件格式解释，有几个疑问希望作者能简单的给个提示，方便后面的参与者能较快的熟悉：

1. https://tieba.baidu.com/p/5381666939?red_tag=0041464978 我按照你给出的参考资料看了这个帖子，这里面贴出的示例代码我尝试着执行了一下，可以导出 obj 模型文件，但是使用 Win10 自带的 3D 查看器或者 3D Max 导入这个模型文件，都没有对应的贴图，但是这个贴图是存在的，比如说 D02.POL 和 d021.dds 。

2. 作者你这个项目编译出来的 model_viewer 可以打开 MV3 文件。我想问 MV3 文件和 POL 文件的区别是什么？因为 model_viewer 可以打开后就有模型和动作，根据我看贴吧的说法，MV3 是人物的动作文件，为什么这个文件既包含了模型，又包含了动作，还包含了贴图呢？

**Comment by leopeng1995** [comment]
UPDATE1: 第一个问题应该是我理解不全，dds 需要通过材质导入到 obj 模型上，目前在 3dmax 里默认导入模型和纹理不对应，贴上去位置会错乱，应该是可以调整位置，我再研究一下。

**Comment by dontpanic92** [comment]
那个帖子稍微有点问题，不能适用于所有的 pol 文件。mv3 确实是动作文件，但是所有的动作都是顶点动画（而不是骨骼动画），因此每一帧其实都是一个完整的模型。mv3里面没有包含贴图，它只制定了贴图名字，贴图文件是放在在同级目录下面的

pol 里就是静态的模型了

**Comment by dontpanic92** [comment]
其实 openpal3 的 model_viewer 也还没做到 100% 读出这些模型，比如 mv3 里面是可以有多个 mesh 的，目前model_viewer 只能显示出第一个
