### ISSUE TITLE
傻逼玩意 ，杂交的玩意！

### ISSUE THREAD

**Issue by flyingfish7** [dontpanic92/OpenPAL3#15]

**Comment by XiaoJueMing** [comment]
you're talking about yourself?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dontpanic92/OpenPAL3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午5:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[dontpanic92/OpenPAL3] 傻逼玩意 ，杂交的玩意！ (#15)

**Comment by dontpanic92** [comment]
无能狂怒？

**Comment by flyingfish7** [comment]
确实 别你这种人 恶心到了

**Comment by flyingfish7** [comment]
> 无能狂怒？
确实 被你这种人 恶心到了
