### ISSUE TITLE
谁提供下Linux版的？

### ISSUE THREAD

**Issue by WaterFloat** [dontpanic92/OpenPAL3#21]
谁提供下Linux版的？
或者提供一个编译教程？

**Comment by dontpanic92** [comment]
刚才的 master build 有点问题，修了一下，应该已经可以正常编译了。

你在用什么发行版？要是 Arch Linux 的话我可以直接发二进制，不是的话我弄一下 AppImage

**Comment by dontpanic92** [comment]
CI 已提供 AppImage 打包版本，目前 `openpal3.toml` 需要手动放在 `~/config/openpal3.toml` 中
