### ISSUE TITLE
实现 Cpk 文件系统读取 C++ Demo

### ISSUE THREAD

**Issue by pengyz** [dontpanic92/OpenPAL3#5]
花了点时间把gbengine.dll中关于CPK文件读取的部分逆向了一下，解压缩部分代码有点乱，没有整理好，其他部分可读性还ok。

本人不会rust，这个demo可以给出实现参考，可以考虑对着翻译成Rust，已经提了PR

**Comment by dontpanic92** [comment]
赞！
