### ISSUE TITLE
正在学Rust，应该怎么编译工程

### ISSUE THREAD

**Issue by pengyz** [dontpanic92/OpenPAL3#7]
按照README中给的步骤编译报错，提示找不到，Cargo.toml，而且openpal3目录里都是C#代码，rust代码不在里面。
Demo工程是哪个？怎么编译？

**Comment by dontpanic92** [comment]
更新了一下 Readme
另外编译完之后需要把 cpk 解压出来，大概是这样的结构
![图片](https://user-images.githubusercontent.com/1056013/81322941-3f1d5500-90c7-11ea-91d9-4930f45ad9e5.png)

然后在 openpal3.toml 里面把 asset_path 更新成这个目录

**Comment by pengyz** [comment]
感谢回复，等会儿我试一下

**Comment by pengyz** [comment]
已经可以运行了，但是控制台有报错，这个是模型文件解析代码还不完善的问题吗？

**Comment by dontpanic92** [comment]
嗯，控制台是随意输出的log，之前有想检查一下那些没解析的字段就打出来了

**Comment by pengyz** [comment]
我这里CG播放一小段后会卡住，现在就是这样的吗？我看到控制台有报错。
能指点一下整个工程怎么调试吗？C#和rust混合的项目 开发环境怎么配置 我配了VSCode，但是好像不管用，rust的异常断不下来

**Comment by dontpanic92** [comment]
嗯，现在就只实现了那一小段cg。加了 C# 之后我还没调试过，之前纯 rust 的时候，用 msvc toolchain 编译后挂上 VS 就可以调试了。

openpal3 现在就是空壳子，计划是之后会放跟游戏逻辑有关的部分，比如人物数据/战斗场景之类的。用 C# 做脚本其实现在还处于实验性质的阶段，不知道最后效果则么样😂

opengb 里也有一些以前在 PAL3.exe 里的功能，比如读场景什么的，我把这些跟游戏逻辑无关的也挪到 opengb 里面去了
